version: "3.9"

services:
  eatwut-auth:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    depends_on:
      - cache
    ports:
      - 9000:9000
      - 8080:8080
    volumes:
      - .:/app
    environment:
      - ENV=dev
      - REDIS_DSN=cache:6379
    restart: always

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
