runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "1.17"
        check-latest: true
        cache: true
    - name: Install dependencies
      shell: bash
      run: go get -u github.com/revel/revel && go get -u github.com/revel/cmd/revel && go mod download
