// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: app/grpc/pb/activation.proto

package rpc_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActiveUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ActiveUserReq) Reset() {
	*x = ActiveUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_pb_activation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveUserReq) ProtoMessage() {}

func (x *ActiveUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_pb_activation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveUserReq.ProtoReflect.Descriptor instead.
func (*ActiveUserReq) Descriptor() ([]byte, []int) {
	return file_app_grpc_pb_activation_proto_rawDescGZIP(), []int{0}
}

func (x *ActiveUserReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_app_grpc_pb_activation_proto protoreflect.FileDescriptor

var file_app_grpc_pb_activation_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x61, 0x75, 0x74, 0x68, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x25, 0x0a, 0x0d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x50, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a,
	0x0a, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f,
	0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_grpc_pb_activation_proto_rawDescOnce sync.Once
	file_app_grpc_pb_activation_proto_rawDescData = file_app_grpc_pb_activation_proto_rawDesc
)

func file_app_grpc_pb_activation_proto_rawDescGZIP() []byte {
	file_app_grpc_pb_activation_proto_rawDescOnce.Do(func() {
		file_app_grpc_pb_activation_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_grpc_pb_activation_proto_rawDescData)
	})
	return file_app_grpc_pb_activation_proto_rawDescData
}

var file_app_grpc_pb_activation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_grpc_pb_activation_proto_goTypes = []interface{}{
	(*ActiveUserReq)(nil), // 0: auth.ActiveUserReq
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_app_grpc_pb_activation_proto_depIdxs = []int32{
	0, // 0: auth.ActivationService.ActiveUser:input_type -> auth.ActiveUserReq
	1, // 1: auth.ActivationService.ActiveUser:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_grpc_pb_activation_proto_init() }
func file_app_grpc_pb_activation_proto_init() {
	if File_app_grpc_pb_activation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_grpc_pb_activation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_grpc_pb_activation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_grpc_pb_activation_proto_goTypes,
		DependencyIndexes: file_app_grpc_pb_activation_proto_depIdxs,
		MessageInfos:      file_app_grpc_pb_activation_proto_msgTypes,
	}.Build()
	File_app_grpc_pb_activation_proto = out.File
	file_app_grpc_pb_activation_proto_rawDesc = nil
	file_app_grpc_pb_activation_proto_goTypes = nil
	file_app_grpc_pb_activation_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ActivationServiceClient is the client API for ActivationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivationServiceClient interface {
	ActiveUser(ctx context.Context, in *ActiveUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type activationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActivationServiceClient(cc grpc.ClientConnInterface) ActivationServiceClient {
	return &activationServiceClient{cc}
}

func (c *activationServiceClient) ActiveUser(ctx context.Context, in *ActiveUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/auth.ActivationService/ActiveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivationServiceServer is the server API for ActivationService service.
type ActivationServiceServer interface {
	ActiveUser(context.Context, *ActiveUserReq) (*emptypb.Empty, error)
}

// UnimplementedActivationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedActivationServiceServer struct {
}

func (*UnimplementedActivationServiceServer) ActiveUser(context.Context, *ActiveUserReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveUser not implemented")
}

func RegisterActivationServiceServer(s *grpc.Server, srv ActivationServiceServer) {
	s.RegisterService(&_ActivationService_serviceDesc, srv)
}

func _ActivationService_ActiveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivationServiceServer).ActiveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.ActivationService/ActiveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivationServiceServer).ActiveUser(ctx, req.(*ActiveUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActivationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.ActivationService",
	HandlerType: (*ActivationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActiveUser",
			Handler:    _ActivationService_ActiveUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/grpc/pb/activation.proto",
}
