// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: app/grpc/pb/profile.proto

package rpc_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAddressData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	District string `protobuf:"bytes,1,opt,name=district,proto3" json:"district,omitempty"`
	City     string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Lat      string `protobuf:"bytes,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng      string `protobuf:"bytes,4,opt,name=lng,proto3" json:"lng,omitempty"`
	Type     string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *UserAddressData) Reset() {
	*x = UserAddressData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_pb_profile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAddressData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddressData) ProtoMessage() {}

func (x *UserAddressData) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_pb_profile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddressData.ProtoReflect.Descriptor instead.
func (*UserAddressData) Descriptor() ([]byte, []int) {
	return file_app_grpc_pb_profile_proto_rawDescGZIP(), []int{0}
}

func (x *UserAddressData) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UserAddressData) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserAddressData) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *UserAddressData) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *UserAddressData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UserProviderData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url              string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Type             string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DisplayOnProfile bool   `protobuf:"varint,3,opt,name=display_on_profile,proto3" json:"display_on_profile,omitempty"`
}

func (x *UserProviderData) Reset() {
	*x = UserProviderData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_pb_profile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserProviderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProviderData) ProtoMessage() {}

func (x *UserProviderData) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_pb_profile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProviderData.ProtoReflect.Descriptor instead.
func (*UserProviderData) Descriptor() ([]byte, []int) {
	return file_app_grpc_pb_profile_proto_rawDescGZIP(), []int{1}
}

func (x *UserProviderData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UserProviderData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserProviderData) GetDisplayOnProfile() bool {
	if x != nil {
		return x.DisplayOnProfile
	}
	return false
}

type UpdateProfileData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName string `protobuf:"bytes,3,opt,name=full_name,proto3" json:"full_name,omitempty"`
	// Types that are assignable to BioOneof:
	//	*UpdateProfileData_Bio
	BioOneof isUpdateProfileData_BioOneof `protobuf_oneof:"bio_oneof"`
	// Types that are assignable to PhoneOneof:
	//	*UpdateProfileData_Phone
	PhoneOneof isUpdateProfileData_PhoneOneof `protobuf_oneof:"phone_oneof"`
	Gender     string                         `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	// Types that are assignable to DobOneof:
	//	*UpdateProfileData_Dob
	DobOneof isUpdateProfileData_DobOneof `protobuf_oneof:"dob_oneof"`
	// Types that are assignable to LastLoginOneof:
	//	*UpdateProfileData_LastLogin
	LastLoginOneof   isUpdateProfileData_LastLoginOneof `protobuf_oneof:"last_login_oneof"`
	Addresses        []*UserAddressData                 `protobuf:"bytes,9,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Providers        []*UserProviderData                `protobuf:"bytes,10,rep,name=providers,proto3" json:"providers,omitempty"`
	PreferCategories []string                           `protobuf:"bytes,11,rep,name=prefer_categories,proto3" json:"prefer_categories,omitempty"`
	// Types that are assignable to IsActiveOneof:
	//	*UpdateProfileData_IsActive
	IsActiveOneof isUpdateProfileData_IsActiveOneof `protobuf_oneof:"is_active_oneof"`
}

func (x *UpdateProfileData) Reset() {
	*x = UpdateProfileData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_pb_profile_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileData) ProtoMessage() {}

func (x *UpdateProfileData) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_pb_profile_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileData.ProtoReflect.Descriptor instead.
func (*UpdateProfileData) Descriptor() ([]byte, []int) {
	return file_app_grpc_pb_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateProfileData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateProfileData) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (m *UpdateProfileData) GetBioOneof() isUpdateProfileData_BioOneof {
	if m != nil {
		return m.BioOneof
	}
	return nil
}

func (x *UpdateProfileData) GetBio() string {
	if x, ok := x.GetBioOneof().(*UpdateProfileData_Bio); ok {
		return x.Bio
	}
	return ""
}

func (m *UpdateProfileData) GetPhoneOneof() isUpdateProfileData_PhoneOneof {
	if m != nil {
		return m.PhoneOneof
	}
	return nil
}

func (x *UpdateProfileData) GetPhone() string {
	if x, ok := x.GetPhoneOneof().(*UpdateProfileData_Phone); ok {
		return x.Phone
	}
	return ""
}

func (x *UpdateProfileData) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (m *UpdateProfileData) GetDobOneof() isUpdateProfileData_DobOneof {
	if m != nil {
		return m.DobOneof
	}
	return nil
}

func (x *UpdateProfileData) GetDob() string {
	if x, ok := x.GetDobOneof().(*UpdateProfileData_Dob); ok {
		return x.Dob
	}
	return ""
}

func (m *UpdateProfileData) GetLastLoginOneof() isUpdateProfileData_LastLoginOneof {
	if m != nil {
		return m.LastLoginOneof
	}
	return nil
}

func (x *UpdateProfileData) GetLastLogin() string {
	if x, ok := x.GetLastLoginOneof().(*UpdateProfileData_LastLogin); ok {
		return x.LastLogin
	}
	return ""
}

func (x *UpdateProfileData) GetAddresses() []*UserAddressData {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *UpdateProfileData) GetProviders() []*UserProviderData {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *UpdateProfileData) GetPreferCategories() []string {
	if x != nil {
		return x.PreferCategories
	}
	return nil
}

func (m *UpdateProfileData) GetIsActiveOneof() isUpdateProfileData_IsActiveOneof {
	if m != nil {
		return m.IsActiveOneof
	}
	return nil
}

func (x *UpdateProfileData) GetIsActive() bool {
	if x, ok := x.GetIsActiveOneof().(*UpdateProfileData_IsActive); ok {
		return x.IsActive
	}
	return false
}

type isUpdateProfileData_BioOneof interface {
	isUpdateProfileData_BioOneof()
}

type UpdateProfileData_Bio struct {
	Bio string `protobuf:"bytes,4,opt,name=bio,proto3,oneof"`
}

func (*UpdateProfileData_Bio) isUpdateProfileData_BioOneof() {}

type isUpdateProfileData_PhoneOneof interface {
	isUpdateProfileData_PhoneOneof()
}

type UpdateProfileData_Phone struct {
	Phone string `protobuf:"bytes,5,opt,name=phone,proto3,oneof"`
}

func (*UpdateProfileData_Phone) isUpdateProfileData_PhoneOneof() {}

type isUpdateProfileData_DobOneof interface {
	isUpdateProfileData_DobOneof()
}

type UpdateProfileData_Dob struct {
	Dob string `protobuf:"bytes,7,opt,name=dob,proto3,oneof"`
}

func (*UpdateProfileData_Dob) isUpdateProfileData_DobOneof() {}

type isUpdateProfileData_LastLoginOneof interface {
	isUpdateProfileData_LastLoginOneof()
}

type UpdateProfileData_LastLogin struct {
	LastLogin string `protobuf:"bytes,8,opt,name=last_login,proto3,oneof"`
}

func (*UpdateProfileData_LastLogin) isUpdateProfileData_LastLoginOneof() {}

type isUpdateProfileData_IsActiveOneof interface {
	isUpdateProfileData_IsActiveOneof()
}

type UpdateProfileData_IsActive struct {
	IsActive bool `protobuf:"varint,12,opt,name=is_active,proto3,oneof"`
}

func (*UpdateProfileData_IsActive) isUpdateProfileData_IsActiveOneof() {}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *UpdateProfileData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_pb_profile_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_pb_profile_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_pb_profile_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileRequest) GetData() *UpdateProfileData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProfileUserAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	District string `protobuf:"bytes,2,opt,name=district,proto3" json:"district,omitempty"`
	City     string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Lat      string `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng      string `protobuf:"bytes,5,opt,name=lng,proto3" json:"lng,omitempty"`
	Type     string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ProfileUserAddress) Reset() {
	*x = ProfileUserAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_pb_profile_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileUserAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUserAddress) ProtoMessage() {}

func (x *ProfileUserAddress) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_pb_profile_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUserAddress.ProtoReflect.Descriptor instead.
func (*ProfileUserAddress) Descriptor() ([]byte, []int) {
	return file_app_grpc_pb_profile_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileUserAddress) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProfileUserAddress) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *ProfileUserAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ProfileUserAddress) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *ProfileUserAddress) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *ProfileUserAddress) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ProfileUserProvider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url              string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Type             string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	DisplayOnProfile bool   `protobuf:"varint,4,opt,name=display_on_profile,json=displayOnProfile,proto3" json:"display_on_profile,omitempty"`
}

func (x *ProfileUserProvider) Reset() {
	*x = ProfileUserProvider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_pb_profile_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileUserProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUserProvider) ProtoMessage() {}

func (x *ProfileUserProvider) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_pb_profile_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUserProvider.ProtoReflect.Descriptor instead.
func (*ProfileUserProvider) Descriptor() ([]byte, []int) {
	return file_app_grpc_pb_profile_proto_rawDescGZIP(), []int{5}
}

func (x *ProfileUserProvider) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProfileUserProvider) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProfileUserProvider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProfileUserProvider) GetDisplayOnProfile() bool {
	if x != nil {
		return x.DisplayOnProfile
	}
	return false
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName string `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// Types that are assignable to BioOneof:
	//	*UpdateProfileResponse_Bio
	BioOneof isUpdateProfileResponse_BioOneof `protobuf_oneof:"bio_oneof"`
	// Types that are assignable to PhoneOneof:
	//	*UpdateProfileResponse_Phone
	PhoneOneof isUpdateProfileResponse_PhoneOneof `protobuf_oneof:"phone_oneof"`
	Gender     string                             `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	// Types that are assignable to DobOneof:
	//	*UpdateProfileResponse_Dob
	DobOneof isUpdateProfileResponse_DobOneof `protobuf_oneof:"dob_oneof"`
	// Types that are assignable to LastLoginOneof:
	//	*UpdateProfileResponse_LastLogin
	LastLoginOneof   isUpdateProfileResponse_LastLoginOneof `protobuf_oneof:"last_login_oneof"`
	Addresses        []*ProfileUserAddress                  `protobuf:"bytes,10,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Providers        []*ProfileUserProvider                 `protobuf:"bytes,11,rep,name=providers,proto3" json:"providers,omitempty"`
	PreferCategories []string                               `protobuf:"bytes,12,rep,name=prefer_categories,json=preferCategories,proto3" json:"prefer_categories,omitempty"`
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_pb_profile_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_pb_profile_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_pb_profile_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProfileResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateProfileResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (m *UpdateProfileResponse) GetBioOneof() isUpdateProfileResponse_BioOneof {
	if m != nil {
		return m.BioOneof
	}
	return nil
}

func (x *UpdateProfileResponse) GetBio() string {
	if x, ok := x.GetBioOneof().(*UpdateProfileResponse_Bio); ok {
		return x.Bio
	}
	return ""
}

func (m *UpdateProfileResponse) GetPhoneOneof() isUpdateProfileResponse_PhoneOneof {
	if m != nil {
		return m.PhoneOneof
	}
	return nil
}

func (x *UpdateProfileResponse) GetPhone() string {
	if x, ok := x.GetPhoneOneof().(*UpdateProfileResponse_Phone); ok {
		return x.Phone
	}
	return ""
}

func (x *UpdateProfileResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (m *UpdateProfileResponse) GetDobOneof() isUpdateProfileResponse_DobOneof {
	if m != nil {
		return m.DobOneof
	}
	return nil
}

func (x *UpdateProfileResponse) GetDob() string {
	if x, ok := x.GetDobOneof().(*UpdateProfileResponse_Dob); ok {
		return x.Dob
	}
	return ""
}

func (m *UpdateProfileResponse) GetLastLoginOneof() isUpdateProfileResponse_LastLoginOneof {
	if m != nil {
		return m.LastLoginOneof
	}
	return nil
}

func (x *UpdateProfileResponse) GetLastLogin() string {
	if x, ok := x.GetLastLoginOneof().(*UpdateProfileResponse_LastLogin); ok {
		return x.LastLogin
	}
	return ""
}

func (x *UpdateProfileResponse) GetAddresses() []*ProfileUserAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *UpdateProfileResponse) GetProviders() []*ProfileUserProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *UpdateProfileResponse) GetPreferCategories() []string {
	if x != nil {
		return x.PreferCategories
	}
	return nil
}

type isUpdateProfileResponse_BioOneof interface {
	isUpdateProfileResponse_BioOneof()
}

type UpdateProfileResponse_Bio struct {
	Bio string `protobuf:"bytes,5,opt,name=bio,proto3,oneof"`
}

func (*UpdateProfileResponse_Bio) isUpdateProfileResponse_BioOneof() {}

type isUpdateProfileResponse_PhoneOneof interface {
	isUpdateProfileResponse_PhoneOneof()
}

type UpdateProfileResponse_Phone struct {
	Phone string `protobuf:"bytes,6,opt,name=phone,proto3,oneof"`
}

func (*UpdateProfileResponse_Phone) isUpdateProfileResponse_PhoneOneof() {}

type isUpdateProfileResponse_DobOneof interface {
	isUpdateProfileResponse_DobOneof()
}

type UpdateProfileResponse_Dob struct {
	Dob string `protobuf:"bytes,8,opt,name=dob,proto3,oneof"`
}

func (*UpdateProfileResponse_Dob) isUpdateProfileResponse_DobOneof() {}

type isUpdateProfileResponse_LastLoginOneof interface {
	isUpdateProfileResponse_LastLoginOneof()
}

type UpdateProfileResponse_LastLogin struct {
	LastLogin string `protobuf:"bytes,9,opt,name=last_login,json=lastLogin,proto3,oneof"`
}

func (*UpdateProfileResponse_LastLogin) isUpdateProfileResponse_LastLoginOneof() {}

var File_app_grpc_pb_profile_proto protoreflect.FileDescriptor

var file_app_grpc_pb_profile_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x22, 0x79, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x68, 0x0a, 0x10,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x5f, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x12, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6f, 0x6e, 0x5f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0xe6, 0x03, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c,
	0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x03,
	0x62, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x62, 0x69, 0x6f,
	0x12, 0x16, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x03, 0x64, 0x6f, 0x62, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52,
	0x03, 0x64, 0x6f, 0x62, 0x12, 0x20, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x33, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x70, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12,
	0x1e, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x04, 0x52, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x42,
	0x0b, 0x0a, 0x09, 0x62, 0x69, 0x6f, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x0d, 0x0a, 0x0b,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x0b, 0x0a, 0x09, 0x64,
	0x6f, 0x62, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x12, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x11, 0x0a, 0x0f,
	0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22,
	0x43, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6c, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x79, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x2c, 0x0a, 0x12, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6f, 0x6e, 0x5f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x4f, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0xca,
	0x03, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75,
	0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x62, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x03, 0x64,
	0x6f, 0x62, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x03, 0x64, 0x6f, 0x62, 0x12,
	0x1f, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x36, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x09, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x0b,
	0x0a, 0x09, 0x62, 0x69, 0x6f, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x0d, 0x0a, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x0b, 0x0a, 0x09, 0x64, 0x6f,
	0x62, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x12, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x32, 0x5c, 0x0a, 0x0e, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a,
	0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1a,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x61,
	0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_grpc_pb_profile_proto_rawDescOnce sync.Once
	file_app_grpc_pb_profile_proto_rawDescData = file_app_grpc_pb_profile_proto_rawDesc
)

func file_app_grpc_pb_profile_proto_rawDescGZIP() []byte {
	file_app_grpc_pb_profile_proto_rawDescOnce.Do(func() {
		file_app_grpc_pb_profile_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_grpc_pb_profile_proto_rawDescData)
	})
	return file_app_grpc_pb_profile_proto_rawDescData
}

var file_app_grpc_pb_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_grpc_pb_profile_proto_goTypes = []interface{}{
	(*UserAddressData)(nil),       // 0: user.UserAddressData
	(*UserProviderData)(nil),      // 1: user.UserProviderData
	(*UpdateProfileData)(nil),     // 2: user.UpdateProfileData
	(*UpdateProfileRequest)(nil),  // 3: user.UpdateProfileRequest
	(*ProfileUserAddress)(nil),    // 4: user.ProfileUserAddress
	(*ProfileUserProvider)(nil),   // 5: user.ProfileUserProvider
	(*UpdateProfileResponse)(nil), // 6: user.UpdateProfileResponse
}
var file_app_grpc_pb_profile_proto_depIdxs = []int32{
	0, // 0: user.UpdateProfileData.addresses:type_name -> user.UserAddressData
	1, // 1: user.UpdateProfileData.providers:type_name -> user.UserProviderData
	2, // 2: user.UpdateProfileRequest.data:type_name -> user.UpdateProfileData
	4, // 3: user.UpdateProfileResponse.addresses:type_name -> user.ProfileUserAddress
	5, // 4: user.UpdateProfileResponse.providers:type_name -> user.ProfileUserProvider
	3, // 5: user.ProfileService.UpdateProfile:input_type -> user.UpdateProfileRequest
	6, // 6: user.ProfileService.UpdateProfile:output_type -> user.UpdateProfileResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_app_grpc_pb_profile_proto_init() }
func file_app_grpc_pb_profile_proto_init() {
	if File_app_grpc_pb_profile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_grpc_pb_profile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAddressData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_pb_profile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserProviderData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_pb_profile_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_pb_profile_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_pb_profile_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileUserAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_pb_profile_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileUserProvider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_pb_profile_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_app_grpc_pb_profile_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*UpdateProfileData_Bio)(nil),
		(*UpdateProfileData_Phone)(nil),
		(*UpdateProfileData_Dob)(nil),
		(*UpdateProfileData_LastLogin)(nil),
		(*UpdateProfileData_IsActive)(nil),
	}
	file_app_grpc_pb_profile_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*UpdateProfileResponse_Bio)(nil),
		(*UpdateProfileResponse_Phone)(nil),
		(*UpdateProfileResponse_Dob)(nil),
		(*UpdateProfileResponse_LastLogin)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_grpc_pb_profile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_grpc_pb_profile_proto_goTypes,
		DependencyIndexes: file_app_grpc_pb_profile_proto_depIdxs,
		MessageInfos:      file_app_grpc_pb_profile_proto_msgTypes,
	}.Build()
	File_app_grpc_pb_profile_proto = out.File
	file_app_grpc_pb_profile_proto_rawDesc = nil
	file_app_grpc_pb_profile_proto_goTypes = nil
	file_app_grpc_pb_profile_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, "/user.ProfileService/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.ProfileService/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateProfile",
			Handler:    _ProfileService_UpdateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/grpc/pb/profile.proto",
}
