name: CD

on: [pull_request]

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: build
        run: revel package .
  publish-image:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build the Docker image
        run: |
          docker build --tag ghcr.io/eatiplaner/eatiplan-authentication-service:latest -f Dockerfile.prod .
          docker push ghcr.io/eatiplaner/eatiplan-authentication-service:latest
